language: elixir
jobs:
  include:
    - elixir: 1.10.4
      otp_release: 23.0
      script:
        - mix format --check-formatted
        - mix compile --warning-as-errors
        - mix test
    - elixir: 1.11
      otp_release: 23.0
      script:
        - mix format --check-formatted
        - mix compile --warning-as-errors
        - mix test

